spring.application.name=ms-Monitoreo
server.port=8084

# MySQL Laragon
spring.datasource.url=jdbc:mysql://localhost:3306/db_monitoreo?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL del microservicio Horario, notificado cuando se crea una alerta
horario.service.url=http://localhost:8082/api/horarios/actualizar

# JWT
jwt.secret=MonitoreoJWTSecretKey2024XYZABCDEFGHIJKLMNabcdefghijklmn12345678
jwt.expiration=86400000

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
